# Generated by Django 3.2 on 2022-12-29 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_auto_20221229_0812'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Title',
            new_name='Titles',
        ),
    ]
